# -*- coding: utf-8 -*-
"""Projeto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlwPqQ7A2VjYZ08pQjeGfOMSXpRJOa5d
"""



"""# Etapa 1

Inserindo dados

"""

num1 = float(input("digite o primeiro número:" ))
num2 = float(input("digite o segundo número:" ))
print("qual operação você deseja fazer2")
print("\t 1º adição")
print("\t 2º subtração")
print("\t 3º multiplicação")
print("\t 4º divisão")

op = input("digite o valor entre (1-4)?")
if (op == "1"):
    print(num1, "+", num2, " = ", num1+num2)
elif(op == "2"):
    print(num1, "-", num2, " = ", num1 - num2)
elif(op == "3"):
    print(num1, "*", num2, " = ", num1 * num2)
elif(op == "4"):
    print(num1, "/", num2, " = ", num1 / num2)
else:
      print("você adicionou uma opção inválida!, tente novamente")

